### ISSUE TITLE
2.0 - Site management section missing from admin

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2276]
![image](https://user-images.githubusercontent.com/5147603/53428364-e5d87280-39a7-11e9-9032-a43bc4f459c2.png)

**Comment by makitso** [comment]
Well well, fails on Chrome both on linux and windows10 but works on FF and Edge.

**Comment by makitso** [comment]
If you delete display: -webkit-flex and display: flex: that fixes the problem.
Html
<div clas-"card mb-4">
vendor.min.cs 
.card {
    position: relative;
    display: -webkit-box;
    display: -webkit-flex;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
}

**Comment by fisharebest** [comment]
The problem still occurs with the original vendor.css file, so it's not causes by the post-processing.

Presumably this is either a bug in our markup or a bug in Bootstrap.

My HTML validator says the page is OK.  I'll look again later.

**Comment by makitso** [comment]
Looks like a bootstrap error.  They went to -webkit-box and -webkit-flex.  Both are lined out but are being used.

Here is github current:
![image](https://user-images.githubusercontent.com/5147603/53510485-5c927000-3a7b-11e9-9a3a-17f337f8a1a8.png)

Here is my web site using github 2/27/19

![image](https://user-images.githubusercontent.com/5147603/53510598-9f544800-3a7b-11e9-8b92-2789e91af460.png)

**Comment by xmlf** [comment]
Yes, my chrome browser is also displaying errors.
![control panel](https://user-images.githubusercontent.com/26761596/53535154-b4dd7680-3b3c-11e9-8a23-30e288df8ef0.JPG)

It is normal on edge and ie.

**Comment by fisharebest** [comment]
I found a bug report for Bootstrap 4.0, where they described tables inside cards as a "shitshow", and "won't fix"..

Adding the class `d-block` to the `<div class="card mb-4...` seems to work for me (Chrome 74 on Mac).

I've committed this change.  Can you test this on your environment?

**Comment by makitso** [comment]
Sorry, patch did not fix the problem -- tested on Windows 10 and Ubuntu 18.10

**Comment by makitso** [comment]
Think you need to move this to line 7

**Comment by fisharebest** [comment]
Which version of Chrome are you using?

**Comment by makitso** [comment]
On linux I am using Version 72.0.3626.119 (Official Build) (64-bit)
It fails on my new iPad Pro, don't know what version Chrome is :-(
Windows 10 Version 72.0.3626.119 (Official Build) (32-bit)

**Comment by makitso** [comment]
If you add d-block to all the <div> statements that have card mb-4 it seems to fix the problem.

**Comment by makitso** [comment]
Looks like the dev version  74.0.3717.0 Dev 64 bit and the beta version 73.0.3683.56 Beta 64 bit both work.  So, its just the stable release.

**Comment by xmlf** [comment]
> If you add d-block to all the div statements that have card mb-4 it seems to fix the problem.

YES.
All class="card mb-4" in the file must be modified to class="card mb-4 d-block
I have modified it and the display is normal in both chrome and edge.
