### ISSUE TITLE
Forms using GET redirect to home page

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2607]
When you do a search on web site logs it takes you back to My Page.

**Comment by fisharebest** [comment]
This is affecting all forms with `method="get"`

**Comment by makitso** [comment]
Original problem is still there.

**Comment by fisharebest** [comment]
It's working for me.  I just tried it on the demo server...

**Comment by makitso** [comment]
???  I just did a Meld on git and my local dev site and everything is in sync.
Is there something I can check to discover what the problem is?

**Comment by makitso** [comment]
Here is the log from when I hit the search button:

::1 - - [09/Oct/2019:16:52:10 -0700] "GET /index.php?route=http%3A%2F%2Flocalhost%2Findex.php%3Froute%3D%252Fadmin%252Fadmin-site-logs&action=show&from=2019-09-13&to=2019-10-09&type=&ip=&text=&username=&gedc= HTTP/1.1" 302 383 "http://localhost/index.php?route=%2Fadmin%2Fadmin-site-logs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

::1 - - [09/Oct/2019:16:52:10 -0700] "GET /index.php?route=%2Fmy-page&tree=peters HTTP/1.1" 200 6021 "http://localhost/index.php?route=%2Fadmin%2Fadmin-site-logs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

::1 - - [09/Oct/2019:16:52:10 -0700] "GET /public/public/ckeditor-4.11.2-custom/ckeditor.js HTTP/1.1" 404 537 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

::1 - - [09/Oct/2019:16:52:10 -0700] "GET /public/public/ckeditor-4.11.2-custom/adapters/jquery.js HTTP/1.1" 404 544 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

**Comment by fisharebest** [comment]
In your file `data/config.ini.php`, add the following line

`base_url="http://your.site.com/path"`

(No trailing slash)

**Comment by makitso** [comment]
So, since I am running on my desktop dev system is would be 
base_url="localhost/path"

**Comment by fisharebest** [comment]
You'd need the `http://` prefix.

**Comment by makitso** [comment]
base_url="http://localhost/path" 
resulted in The requested URL /path/index.php was not found on this server.
Logs
::1 - - [10/Oct/2019:04:20:35 -0700] "GET /index.php HTTP/1.1" 302 580 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:20:35 -0700] "GET /path/index.php?route=%2Fpath%2Ftree-page&ged=peters HTTP/1.1" 404 503 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:20:35 -0700] "GET /favicon.ico HTTP/1.1" 200 15388 "http://localhost/path/index.php?route=%2Fpath%2Ftree-page&ged=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

**Comment by fisharebest** [comment]
Dumb question.  Did you really install webtrees in a folder called `path`?

**Comment by makitso** [comment]
The apache2.conf has these entries:
<Directory /home/rob/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>
ServerName localhost

**Comment by fisharebest** [comment]
When I said `base_url="http://your.site.com/path"`, I meant that you show substitute your own domain **AND** your path.

**Comment by fisharebest** [comment]
If you didn't install webtrees in a folder, then the path will be empty.

e.g. `base_url="http://localhost"`

**Comment by makitso** [comment]
Added base_url="http://localhost"  to config.ini.php
Site now works.
Problem still exists, Log says:
::1 - - [10/Oct/2019:04:55:45 -0700] "GET /public/public/ckeditor-4.11.2-custom/adapters/jquery.js HTTP/1.1" 404 544 "http://localhost/index.php?route=%2Fadmin%2Fadmin-site-logs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /index.php?route=http%3A%2F%2Flocalhost%2Findex.php%3Froute%3D%252Fadmin%252Fadmin-site-logs&action=show&from=2019-09-13&to=2019-10-10&type=&ip=&text=&username=&gedc= HTTP/1.1" 302 383 "http://localhost/index.php?route=%2Fadmin%2Fadmin-site-logs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /index.php?route=%2Fmy-page&tree=peters HTTP/1.1" 200 6024 "http://localhost/index.php?route=%2Fadmin%2Fadmin-site-logs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /public/public/ckeditor-4.11.2-custom/ckeditor.js HTTP/1.1" 404 537 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /public/public/ckeditor-4.11.2-custom/adapters/jquery.js HTTP/1.1" 404 544 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /public/public/ckeditor-4.11.2-custom/ckeditor.js HTTP/1.1" 404 537 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /public/public/ckeditor-4.11.2-custom/adapters/jquery.js HTTP/1.1" 404 544 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /index.php?route=%2Fuser-page-block&ged=peters&block_id=12 HTTP/1.1" 200 1667 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /index.php?route=%2Fuser-page-block&ged=peters&block_id=8 HTTP/1.1" 200 1126 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /index.php?route=%2Fmedia-thumbnail&s=f694c98973ad018ce6e6e0d974c91812&xref=M44&ged=peters&fact_id=eec41e92e66024a2cbfc435c97de2232&w=200&h=200&fit=&mark=&markh=100h&markw=100w&markalpha=25&or=0 HTTP/1.1" 200 13394 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:04:56:11 -0700] "GET /index.php?route=%2Fuser-page-block&ged=peters&block_id=13 HTTP/1.1" 200 1916 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

**Comment by fisharebest** [comment]
> Problem still exists, Log says:
> ::1 - - [10/Oct/2019:04:55:45 -0700] "GET /public/public/ckeditor-4.11.2-custom/adapters/jquery.js

The double `public` in this path was fixed a few minutes ago...

**Comment by makitso** [comment]
Sorry, after the pull the problem still exists.  Interesting that if I download it work correctly and if I delete it works correctly, only the search function fails i.e. routes me to My Page

**Comment by makitso** [comment]
Select website logs option:
::1 - - [10/Oct/2019:05:12:16 -0700] "GET /index.php?route=%2Fadmin%2Fadmin-site-logs HTTP/1.1" 200 2718 "http://localhost/index.php?route=%2Fadmin%2Fadmin-control-panel" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

Select search option:

::1 - - [10/Oct/2019:05:13:14 -0700] "GET /index.php?route=http%3A%2F%2Flocalhost%2Findex.php%3Froute%3D%252Fadmin%252Fadmin-site-logs&action=show&from=2019-10-10&to=2019-10-10&type=&ip=&text=&username=&gedc= HTTP/1.1" 302 383 "http://localhost/index.php?route=%2Fadmin%2Fadmin-site-logs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:05:13:14 -0700] "GET /index.php?route=%2Fmy-page&tree=peters HTTP/1.1" 200 6024 "http://localhost/index.php?route=%2Fadmin%2Fadmin-site-logs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:05:13:14 -0700] "GET /index.php?route=%2Fuser-page-block&ged=peters&block_id=12 HTTP/1.1" 200 1657 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:05:13:14 -0700] "GET /index.php?route=%2Fuser-page-block&ged=peters&block_id=8 HTTP/1.1" 200 1126 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:05:13:14 -0700] "GET /index.php?route=%2Fmedia-thumbnail&s=0a78395b8ab6705f773533eeab0a12cb&xref=M94&ged=peters&fact_id=bfe68161f86a3991e7dc65ab2be08f4b&w=200&h=200&fit=&mark=&markh=100h&markw=100w&markalpha=25&or=0 HTTP/1.1" 200 8431 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
::1 - - [10/Oct/2019:05:13:14 -0700] "GET /index.php?route=%2Fuser-page-block&ged=peters&block_id=13 HTTP/1.1" 200 1916 "http://localhost/index.php?route=%2Fmy-page&tree=peters" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

**Comment by makitso** [comment]
I sync'ed my production site on skatekey.net and the search still routes to My Page

**Comment by fisharebest** [comment]
I've just re-written the logic for detecting base URL and request URL.

Can you tell me if it fixes the problem?

**Comment by makitso** [comment]
So, I am not sure what is going on.  I was going to try a clean install but issue #2621 blocked me from doing this.  So, I  imported a backup of my dev system and now logging in seems to work, i.e. it sends me to the home page.  My test site does have th "Working on Routing" patch you c omitted two hours ago.  Let me sync my production system and see if it works there.

**Comment by makitso** [comment]
OK, sync'ed my local changes up to my production system and now routing works correctly on login.
