### ISSUE TITLE
github - wrong routing on sign-in / sign-out/ sign-in

### ISSUE THREAD

**Issue by makitso** [fisharebest/webtrees#2672]
Login in.
Go to Control panel / Website logs
Sign out
Sign in results in blank page
Logs:
::1 - - [21/Oct/2019:06:09:36 -0700] "POST /index.php?route=%2Flogout HTTP/1.1" 200 1532 "http://localhost/index.php?route=%2Fadmin%2Flogs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:09:36 -0700] "GET /index.php?route=%2Fadmin%2Flogs HTTP/1.1" 302 439 "http://localhost/index.php?route=%2Fadmin%2Flogs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:09:36 -0700] "GET /index.php?route=%2Flogin HTTP/1.1" 200 3512 "http://localhost/index.php?route=%2Fadmin%2Flogs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
::1 - - [21/Oct/2019:06:09:46 -0700] "POST /index.php?route=%2Flogin HTTP/1.1" 302 415 "http://localhost/index.php?route=%2Flogin" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

**Comment by fisharebest** [comment]
I think this may have been fixed by 57bfa969ae5adb60a68faad19182a580933467cd

I can't reproduce it now.

**Comment by makitso** [comment]
Problem still exists.
Login
Select Control panel
Log out
Log in

**Comment by fisharebest** [comment]
Try again.  It may have been fixed by 8753199a9f264be84483c19ae25f7cc98b50e3a1

**Comment by makitso** [comment]
Sorry, did not fix.

**Comment by fisharebest** [comment]
What URL do you see with the blank page?

**Comment by makitso** [comment]
http://localhost/index.php?route=%2Flogin
It does not change from the login page.
But, I am logged in

**Comment by makitso** [comment]
Greg,  The problem only happens when I sign out while on the Control panel page.  
AND, it only fails on Chrome and Brave browsers on Linux, not on the latest Firefox.

**Comment by makitso** [comment]
Curious:  Here is the normal login page:
![image](https://user-images.githubusercontent.com/5147603/67626296-fe7e7e00-f7fd-11e9-8fdc-d08c10f49856.png)

Here is the login page when I sign out from the Control panel:
![image](https://user-images.githubusercontent.com/5147603/67626304-21109700-f7fe-11e9-9291-dafb943d524d.png)

**Comment by makitso** [comment]
Fails on Windows 10 and Chrome, but not on Edge.
Tried a clean install of Chrome, w/o plugins, etc and it fails.
Fails on Chromebook and Chrome.

**Comment by fisharebest** [comment]
A redirect is created with a `Location` HTTP header.

These are supposed to be absolute URLs.

However, most (all) browsers will accept a relative URL.

If the `Location` header is empty, Firefox seems to treat it as a relative URL, and leaves you on the current page.  However Chrome ignores the empty header, and leaves you on a page with no content.

The login process stores a "redirect URL", which is where we need to return to after the login.

There is case where this redirect URL can be empty.  So, fixing this empty URL will fix the problem.
