### ISSUE TITLE
2.1.7  Unsupported driver [sqlsvr] DB Setup

### ISSUE THREAD

**Issue by FrankWarius** [fisharebest/webtrees#4567]
Unsupported driver [sqlsvr].
#0 D:\web\wbt\vendor\illuminate\database\Connectors\ConnectionFactory.php(76): Illuminate\Database\Connectors\ConnectionFactory->createConnection('sqlsvr', Object(Closure), 'WTProd', 'wt21_', Array)
#1 D:\web\wbt\vendor\illuminate\database\Connectors\ConnectionFactory.php(50): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#2 D:\web\wbt\vendor\illuminate\database\DatabaseManager.php(140): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'default')
#3 D:\web\wbt\vendor\illuminate\database\DatabaseManager.php(95): Illuminate\Database\DatabaseManager->makeConnection('default')
#4 D:\web\wbt\vendor\illuminate\database\Capsule\Manager.php(109): Illuminate\Database\DatabaseManager->connection('default')
#5 D:\web\wbt\vendor\illuminate\database\Capsule\Manager.php(74): Illuminate\Database\Capsule\Manager->getConnection(NULL)

in $driver for MS SQL Server we use both "sqls**rv**" and "sqls**vr**" (see case 'sqlsrv': in line 283 in  createConnection())

I'm starting to patch the bugs locally and will report back.

**Comment by fisharebest** [comment]
> I'm starting to patch the bugs locally and will report back.

Thanks.

I don't have access to MS SQL-Server, so never tested this.

**Comment by FrankWarius** [comment]
I stupid changed sqlsvr to sqlsrv in 2 file and renamed one.
![grafik](https://user-images.githubusercontent.com/16499744/193584460-281e951f-d2d9-4239-9ffc-a66a2d927a63.png)

now I get a PDO error:
could not find driver (SQL: create table "wt_gedcom" ("gedcom_id" int identity primary key not null, "gedcom_name" nvarchar(255) not null, "sort_order" int not null default '0'))
#0 D:\web\WT21Prod\vendor\illuminate\database\Connection.php(672): Illuminate\Database\Connection->runQueryCallback('create table "w...', Array, Object(Closure))
#1 D:\web\WT21Prod\vendor\illuminate\database\Connection.php(502): Illuminate\Database\Connection->run('create table "w...', Array, Object(Closure))
#2 D:\web\WT21Prod\vendor\illuminate\database\Schema\Blueprint.php(109): Illuminate\Database\Connection->statement('create table "w...')

This leads us to https://dev.to/mr_steelze/setting-up-a-laravel-project-with-sql-server-and-xampp-wamp-on-windows-3n7k

We need MS PHP SQL Driver

**Comment by fisharebest** [comment]
I think I have fixed this.  Please can you test it?

**Comment by FrankWarius** [comment]
I downloaded the SQL Driver and now get
SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No connection could be made because the target machine actively refused it.
 (SQL: create table "wt21_gedcom" ("gedcom_id" int identity primary key not null, "gedcom_name" nvarchar(255) not null, "sort_order" int not null default '0'))
#0 D:\web\WT21Prod\vendor\illuminate\database\Connection.php(672): Illuminate\Database\Connection->runQueryCallback('create table "w...', Array, ...

This works but I have to change the WTUser rights in SQL

I'll test Yor code later

**Comment by FrankWarius** [comment]
I have just reached the SQL server for the first time when initializing the database. (Now there are still missing rights).

In my installation I can only establish a connection without a port. If no port is specified in the form, there is an HTTP 500 error.

I specified 1433 (default) and removed ",1433" from the $DSN variable during debugging.

Could you adjust accordingly: Optional port empty and no comma.

**Comment by FrankWarius** [comment]
I Changed  Default Port for SQL Server to '' in Setupwizzard.php line 88
```
   private const DEFAULT_PORTS = [
        'mysql'  => '3306',
        'pgsql'  => '5432',
        'sqlite' => '',
        'sqlsrv' => '',
    ];
```
I gave the WT SQL User global admin rights on the server (sysadmin) and the connection was established.
